# -*- coding: utf-8 -*-
"""Project-3 span ham mail Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMmoMjfvWbgyQnA4mRmX9xW_pvr3YXk-

Spam_Mail_Prediction_using_Machine_Learning
- importing libraries
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

"""data collection and handling"""

mail_data=pd.read_csv('/content/mail_data.csv')
mail_data.head()

mail_data.isnull().sum()
mail_data.shape

"""LABEL ENCODING"""

label_encode=LabelEncoder()
mail_data['Category']=label_encode.fit_transform(mail_data['Category'])
mail_data.head()

"""0 ->Ham mail            

1 ->Spam mail
"""

X=mail_data['Message']
Y=mail_data['Category']

"""SPLITING THE DATA INTO TRAINING AND TESTING DATASETS"""

X_train, X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

print(X.shape,X_train.shape,X_test.shape)

"""EXTRACTING FEATURES

converting the text data into numarical values
"""

feature_extraction = TfidfVectorizer(min_df =1,stop_words='english',lowercase=True)

X_train_numarical=feature_extraction.fit_transform(X_train)
X_test_numarical=feature_extraction.fit_transform(X_test)
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

"""creating model ,and feading the traind data to it"""

model=LogisticRegression()

model.fit(X_train_numarical,Y_train)

#predicting
#checkign the accury score

predict_train=model.predict(X_train_numarical)
accury_score=accuracy_score(predict_train,Y_train)
print(accury_score)

predict_test=model.predict(X_test_numarical)
accury_score=accuracy_score(Y_test,predict_test)
print(accury_score)